#!/bin/sh

DIR=/mnt/kiss/usercode/bin
PROG=$DIR/robot
NAME=$DIR/robot_name.txt

rm -rf $DIR
mkdir -p $DIR

echo "Compiling ${1}"
FOLDER="${1%/*}"
/mnt/kiss/usercode/g++-usercode "-I${FOLDER}" "${1}" -o $PROG 2>&1
if [ -e $PROG ]; then
  echo "Compile succeeded." 
  echo "${1}" > $NAME
	exit 0
else
  echo "Compile failed."
	exit 1
fi

