######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 8 15:22:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += png_to_565.cpp
