#!/bin/sh

mkdir -p /mnt/usercode >/dev/null 2>&1
mount /dev/sdb1 /mnt/usercode -t vfat >/dev/null 2>&1
mount /dev/sdc1 /mnt/usercode -t vfat >/dev/null 2>&1
mount /dev/sdd1 /mnt/usercode -t vfat >/dev/null 2>&1
rmdir /mnt/usercode >/dev/null 2>&1

if [ -e /mnt/usercode ]; then
  /mnt/kiss/usercode/compile /mnt/usercode/robot.c 2>&1
	exit $?
else
  echo "Can't find USB key"
fi

umount /mnt/usercode >/dev/null 2>&1

exit 1
