#!/bin/sh

# get the device the internal usb drive is mounted on
INTUSB=`ls -l /dev/disk/by-label/kissys | awk '{print $11}' | sed 's/[0-9]*//g'`
INTUSB=${INTUSB#../../}

# make sure there is an argument containing a mount path
if [ $# -eq 0 ]; then
	exit 1
fi

# the mount location is passed to the script from Qt
USBFOLDER=$1

# create a usb mount point not already taken
#i=1
#USBFOLDER=/mnt/browser/usb$i
#while [ -e $USBFOLDER ]
#do
#    i=$(( i + 1 ))
#   USBFOLDER=/mnt/browser/usb$i
#done

# loop through all the devices
for dev in sda sdb sdc sdd;
do
    # ignore the internal usb device
    if [ "${INTUSB}1" = "${dev}1" ]; then
	continue
    fi
    
    # check if the device is already mounted?
    if [ -z "`mount | grep $dev`" ]; then
	# device not mounted yet make a mount location
	mkdir -p $USBFOLDER >/dev/null 2>&1
	# try mounting the device
	mount /dev/${dev}1 $USBFOLDER -t vfat >/dev/null 2>&1
	if [ -n "`mount | grep $dev`" ]; then
	    # device mounted properly, exit
	    exit 0
	fi
	# mount failed remove the directory
	rmdir $USBFOLDER >/dev/null 2>&1
    fi
done

exit 1
