#!/bin/bash

export LD_LIBRARY_PATH=/lib
CBC_DEBUG=1
KISS=/mnt/kiss
USER=/mnt/user
EXTUSB=/mnt/extusb
VERSION=`cat $KISS/FIRMWARE_VERSION`

if [ "$1" == "--version" ]; then
  echo $VERSION
  exit 0
fi

BROWSER_UPGRADE=""
if [ -e /psp/upgrade ]; then
	BROWSER_UPGRADE=`cat /psp/upgrade`
fi

# make sure a full reflash is possible with the userhook on the root of a usb drive
# and check for browser upgrades on the external usb filesystem
for dev in sdb sdc sdd;
do
	# mount the external usb stick and look for a Userhook0 file on it's root
        mount /dev/${dev}1 $EXTUSB -t vfat -o ro
        if [ -e $EXTUSB/userhook0 ]; then
                $EXTUSB/userhook0 --upgrade &
		exit 0
        # Make sure the string is not null and get the first word in the string ${string%% *}
	elif [ -n $BROWSER_UPGRADE -a -e ${BROWSER_UPGRADE%% *} ]; then
                ${BROWSER_UPGRADE} &
		exit 0
	fi
        umount $EXTUSB
done

if [ ${CBC_DEBUG} -ge 1 ]; then
    PRINT=/psp/fb_print    # causes printing to the screen
	echo "CBC Firmware Version $VERSION" | $PRINT --echo
else
    PRINT=echo
        dd if=$KISS/images/splash_screen.bin of=/dev/fb0
fi

#######################################
# Network setup
#################
# Set up loopback
ifconfig lo 127.0.0.1

# Set up wired network
######################
echo "Checking for network" | $PRINT
echo "Starting wired network driver"
insmod /drivers/pegasus.ko
echo "Starting DHCP on eth0"
udhcpc eth0

# Set up wireless network
#########################
echo "Starting wireless network driver" | $PRINT
#insmod /drivers/rt73.ko
insmod $KISS/drivers/rt73.ko
if [ -e $KISS/config/network_config ]; then
	echo "Copying network config" | $PRINT
    cp $KISS/config/network_config /psp
	/usr/chumby/scripts/start_network &
else
	if [ -e /psp/network_config ]; then
            echo "Starting network" | $PRINT
            /usr/chumby/scripts/start_network &
	else
            echo "Raising usb network" | $PRINT
            ifconfig rausb0 up
	fi
fi

# Display network interfaces
############################
echo "ifconfig in 5" | $PRINT
sleep 5
#ifconfig | $PRINT
ifconfig | grep inet | grep -v 127.0.0.1 | sed 's/Bcast.*//' | $PRINT

# sshd
######
echo "Starting sshd" | $PRINT
/sbin/sshd

##############################
# Chumby Hardware driver setup
##############################
# Touch screen and sensors
hwversion=`/usr/chumby/scripts/chumby_version -h`
echo "Chumby hardware version $hwversion" | $PRINT --echo
if [ "$hwversion" == "3.8" ]; then
    # touch screen
    insmod /drivers/chumby-tsc2100.ko version038=1

    # chumby sensor driver
    insmod /drivers/chumby_sense1.ko version038=1
else
    # touch screen
    insmod /drivers/chumby-tsc2100.ko

    # chumby sensor driver
    insmod /drivers/chumby_sense1.ko
fi
#echo "Disabling touchscreen touchclick"
echo 0 > /proc/chumby/touchscreen/touchclick

# USB HID: keyboard / mouse
###########################
echo "Starting USB HID" | $PRINT
insmod /drivers/usbhid.ko
insmod /drivers/chumby_udma.ko
insmod /drivers/chumby_timer.ko
mknod /dev/timerx c `cat /proc/devices |awk '/timer/ {print $1}'` 0
mknod /dev/timerm c `cat /proc/devices |awk '/timer/ {print $1}'` 1

# chumby switch
mknod /dev/switch c `cat /proc/devices |awk '/switch/ {print $1}'` 0

# chumby udma
mknod /dev/udma c `cat /proc/devices |awk '/udma/ {print $1}'` 1

# set paranoid boot flag/semaphore
echo "Clearing paranoid boot flag" | $PRINT
/bin/eraseall /dev/mtd7
nandwrite /dev/mtd7 /usr/chumby/msp_00_64k_no_oob.bin 0x70000

echo "Loading CBOB SPI module" | $PRINT
insmod $KISS/drivers/cbob.ko
sh $KISS/drivers/mkdev.sh

restore_time

KISS_DEV=/dev/disk/by-label/kissys
USER_DEV=/dev/disk/by-label/userpart

#echo -n "Checking internal filesystems..." | $PRINT
#$KISS/drivers/fsck.ext2 -y ${USER_DEV} | $PRINT
#echo "done." | $PRINT

mkdir -p /mnt/browser/code
mount --bind /mnt/user/code /mnt/browser/code

#######################
# Setup audio
#############
echo "Enabling audio" | $PRINT
insmod /drivers/snd-rawmidi.ko
insmod /drivers/snd-seq-midi.ko
insmod /drivers/snd-usb-lib.ko
insmod /drivers/snd-hwdep.ko
insmod /drivers/snd-usb-audio.ko

echo "Startup btplay daemon" | $PRINT
btplayd </dev/null >/dev/null 2>&1 &
sleep 2
chmod a+w /tmp/.btplay-cmdin
btplay $KISS/sounds/mellow.wav
sleep 2
btplay $KISS/sounds/sysInit.wav

save_time

echo "" | $PRINT --echo
echo "Boot complete" | $PRINT --echo

if [ ${CBC_DEBUG} -gt 1 ]; then
	echo "Trying to start control panel" | $PRINT
	/usr/chumby/scripts/start_control_panel
fi
if [ ${CBC_DEBUG} -eq 0 ]; then
    $KISS/gui/startup.sh &
fi
exit
