#!/bin/sh

DIR=/mnt/user/bin
PROG=$DIR/robot
NAME=$DIR/robot_name.txt

rm -rf $DIR
mkdir -p $DIR

echo "Compiling ${1}" 
/mnt/kiss/usercode/gcc-usercode "${1}" -o $PROG 2>&1
if [ -e $PROG ]; then
  echo "Compile succeeded." 
  echo "${1}" > $NAME
else
  echo "Compile failed."
fi

