#!/bin/sh

mkdir -p /mnt/usercode >/dev/null 2>&1
mount /dev/sda1 /mnt/usercode -t vfat >/dev/null 2>&1
mount /dev/sdb1 /mnt/usercode -t vfat >/dev/null 2>&1
mount /dev/sdc1 /mnt/usercode -t vfat >/dev/null 2>&1
mount /dev/sdd1 /mnt/usercode -t vfat >/dev/null 2>&1
rmdir /mnt/usercode >/dev/null 2>&1

if [ -e /mnt/usercode ]; then
    exit 0
else
    exit 1
fi

