#!/bin/sh

mkdir -p /mnt/browser/usb >/dev/null 2>&1
mount /dev/sda1 /mnt/browser/usb -t vfat >/dev/null 2>&1
mount /dev/sdb1 /mnt/browser/usb -t vfat >/dev/null 2>&1
mount /dev/sdc1 /mnt/browser/usb -t vfat >/dev/null 2>&1
mount /dev/sdd1 /mnt/browser/usb -t vfat >/dev/null 2>&1
rmdir /mnt/browser/usb >/dev/null 2>&1

if [ -e /mnt/browser/usb ]; then
    exit 0
else
    exit 1
fi

