#!/bin/sh

USBINT=/mnt/usbint
USBEXT=/mnt/usbext

#PRINT=/psp/rfs1/fb_print
PRINT=echo
chmod +x /psp/rfs1/fb_print

export LD_LIBRARY_PATH=/lib
export CBC_DEBUG=1

echo "Starting udevd as daemon"
/sbin/udevd --daemon

# wait for USB subsystem to finish loading
/usr/chumby/scripts/wait_for_usb

echo "CBC Internal Boot Script" | $PRINT

# check for internal USB stick
if [ ! -d /mnt/usbint ]; then
	# startup terminal console if not there
	exit 1
fi

mkdir -p $USBEXT

if [ -e /psp/rfs1/upgrade ]; then
    upgrade_location=`cat /psp/rfs1/upgrade`
    echo ${upgrade_location}
    rm /psp/rfs1/upgrade
fi

# loop through usb devices to find the userhook0s internal and external
for dev in sda sdb sdd sdc;
do
 # mount a device to location /mnt/usb with type vfat filesystem in a read only state
  mount /dev/${dev}1 /mnt/usb -t vfat -o ro

  if [ -e /mnt/usb/userhook0 ]; then
    type=`/mnt/usb/userhook0 --type`
    
    # found an upgrade on the root of the USB key
    if [ "${type}" == "Upgrade" ]; then
        upgrade_location="/mnt/usb/userhook0"
        upgrade=${dev}
    # boot normally
    elif [ "${type}" == "Firmware" ]; then
      internal=${dev}
    else
      maybe_internal=${dev}
    fi
  elif [ -n "${upgrade_location}" ]; then
    if [ -e ${upgrade_location} -a -z "${upgrade}" ]; then
        upgrade=${dev}
    fi
  else
    maybe_internal=${dev}
  fi

  umount /mnt/usb
done

if [ -z "${internal}" -a -n "${maybe_internal}" ]; then
  internal=${maybe_internal}
fi

if [ -z "${internal}" ]; then
  echo "Could not find any internal drives!" | $PRINT
  exit 1
fi

# if there is no external usb userhook0
if [ -z "${upgrade}" ]; then
  # mount the internal drive
  if [ ${CBC_DEBUG} -eq 0 ]; then
    mount /dev/${internal}1 /mnt/usb -t vfat -o ro
  else
    mount /dev/${internal}1 /mnt/usb -t vfat -o rw
  fi

  # execute the userhook0 if it exists
  if [ -e /mnt/usb/userhook0 ]; then
	 . /mnt/usb/userhook0 ${internal}
    exit 0
  else
    echo "Could not find boot script!" | $PRINT
    exit 1
  fi
fi

# otherwise mount the external drive
mount /dev/${upgrade}1 /mnt/usb -t vfat
# and execute an upgrade
if [ -n "${upgrade_location}" -a -e ${upgrade_location} ]; then
    ${upgrade_location} --upgrade ${internal} &
else
    echo "Could not find Upgrade script!" | $PRINT
fi
exit 0

